### PR TITLE
OpenShift Origin support

### LINKED ISSUE #132: Support OpenShift Origin
This tool seems very useful, but does not currently work with [OpenShift Origin][origin], which is based on Kubernetes. Some fairly minor changes are needed to get Telepresence working with Origin:

1. [x] Allow the remote pod to be run as non-root (#131)
1. [x] Improve logic for identifying the remote pod (related to #130)
1. [x] Allow configuration of the binary to run (e.g. call `oc` instead of `kubectl`)
1. [x] Either:
    1. create a pod directly or
    1. let the server choose which generator to use

For item 4.ii, the generator can be guided by the `--restart` flag to `kubectl/oc run`. When provided `--restart=Always`, [`kubectl` will create a `Deployment`][kubectl-generators] and [`oc` will create a ` DeploymentConfig`][oc-generators].

[origin]: https://github.com/openshift/origin
[kubectl-generators]: https://kubernetes.io/docs/user-guide/kubectl-conventions/#generators
[oc-generators]: https://github.com/openshift/origin/blob/v1.4.1/docs/man/man1/oc-run.1#L43-L45

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #132.

### CODE REVIEW

**Comment by itamarst** [comment]
@elyscape if you've got some time would be nice to get a user testing. I expect to merge this tomorrow, otherwise.

**Comment by elyscape** [comment]
I'll take a look.

**Comment by elyscape** [comment]
It works! As a side note, it might be worthwhile to add the `openssl` package to the Dockerfile, as this allows you to run `wget` against HTTPS endpoints.

**Comment by itamarst** [comment]
@elyscape I just released 0.46 with OpenShift support. Any suggestions for good places to share this with the OpenShift community?

**Comment by mhausenblas** [comment]
Awesome and congrats for shipping this so fast! I [tweeted](https://twitter.com/mhausenblas/status/864898049130233856) about it now and the plan is to use it next week in my talk at ContainerCamp Australia. Will let you know how it goes ;)

**Comment by elyscape** [comment]
@itamarst I'm not quite sure myself, but I shared it in #openshift-dev on Freenode and a couple of channels on [Hangops](https://signup.hangops.com/).

**Comment by elyscape** [comment]
@itamarst It was suggested in #openshift-dev that we post an announcement to [the OpenShift users list](https://lists.openshift.redhat.com/openshiftmm/listinfo/users).

**Comment by itamarst** [comment]
@elyscape I'll send an email there when I'm back from PyCon, unless you'd like to? Thanks for sharing it on hangops/freenode!

**Comment by elyscape** [comment]
@itamarst Apologies for the delayed response.

I think it would make the most sense for you to do it; since it's your project, you're more likely to be able to draft up a proper email that describes it well.

**Comment by itamarst** [comment]
OK, will do - just released new version that has OpenShift tutorial and support for `--swap-deployment`, check it out.

**Comment by elyscape** [comment]
Nice! Will take a look.

**Pull request merged**
