### PR TITLE
Run as non-root user

### LINKED ISSUE #131: Support running the remote image as non-root
Kubernetes is [working on support for Security Contexts][securitycontext]. These would, among other things, allow a cluster to be configured such that pods are prohibited from running as root. In fact, this is the default mode for [OpenShift Origin][origin]. Unfortunately, the Telepresence Docker image needs to be run as root:
```shellsession
scapeless:~ elyscape$ docker run -it --rm --user=1000050000 datawire/telepresence-k8s:0.42
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```
This can be handled with two changes:

1. Bind the SSH daemon to a non-privileged port (i.e. some port >= 1024).
1. Add group read permissions to the files in `/etc/ssh`. When using a custom UID, Kubernetes sets the default group to 0 with a supplemental group equal to the UID. Sample output from inside a pod:
```shellsession
sh-4.2$ id
uid=1000050000 gid=0(root) groups=0(root),1000050000
```

[securitycontext]: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/security_context.md
[origin]: https://github.com/openshift/origin

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #131.

@elyscape will this approach work for OpenShift?

### CODE REVIEW

**Comment by elyscape** [comment]
It should but I have a simpler version that will also work. I'll submit a PR shortly.

**Comment by elyscape** [comment]
Actually, this won't quite work. The call to `runner.check_call()` will fail, and I'm not sure about sshfs. I'm testing that now.

**Comment by elyscape** [comment]
Hmm, it looks like `sshfs` isn't working because it relies on `sftp`. I'm looking into a workaround.

**Comment by elyscape** [comment]
Ultimately, `UsePrivilegeSeparation no` doesn't help if you need to run commands or use a subsystem, and we need to do both. The upshot is that we need to get `getpwnam()` to return the current UID. Since nss_wrapper doesn't exist on Alpine, I'm falling back to the non-ideal solution of allowing the runtime user to write to `/etc/passwd` and having a script that runs at container startup that adds a passwordless user with that UID to the file. See #143.

**Comment by itamarst** [comment]
Superseded by the simpler version in #144.

**Pull request closed without merging**
